### ISSUE TITLE
new account identity token issues

### ISSUE THREAD

**Issue by sojojo** [datasift/datasift-php#38]
Some new issues have surfaced with account identity tokens:

>updating a token that doesn't exist. The whole token management code in the DataSift PHP Client Library seems to be outdated now as the only method still working as expected is DataSift_Account_Identity_Token::get(). Here are more issues to report: 
>Create token: 
>Causes DataSift_Exception_APIError("Content was expected but nothing was returned (Status: 201 and no data)") 
>Stack Trace: 
>in vendor/datasift/datasift-php/lib/DataSift/User.php at line 487 
>case 200: 
>case 201: 
>if (empty($res['data'])) { 
>-> throw new DataSift_Exception_APIError( 
>"Content was expected but nothing was returned (Status: 201 and no data)" 
>); 
>} 
>at DataSift_User ->handleResponse (array('response_code' => '201', 'data' => null, 'rate_limit' => '10000', 'rate_limit_remaining' => '9570')) 
>in vendor/datasift/datasift-php/lib/DataSift/User.php at line 546 
>at DataSift_User ->post ('account/identity/96f668665060e212ad.../token', array('service' => 'facebook', 'token' => '107893235213...')) 
>in vendor/datasift/datasift-php/lib/DataSift/Account/Identity/Token.php at line 78 
>at DataSift_Account_Identity_Token ->create ('96f66866506...', 'facebook', '107893235...') 
>in src/Datasift/ConnectBundle/Service/IdentityService.php at line 309
>
>But the token was actually created: 
>Calling DataSift_Account_Identity_Token->get('96f66866506..., 'facebook') confirms: 
>> 'service' => 'facebook', 
>> 'token' => '107893235213...', 
>> 'created_at' => 1438350635, 
>> 'updated_at' => 1438350635, 
>> 'expires_at' => NULL,
>
>Update token: 
>Causes DataSift_Exception_AccessDenied("Authorization credentials missing") 
>Stack Trace: 
>in vendor/datasift/datasift-php/lib/DataSift/User.php at line 496 
>$retval = $res['data']; 
>break; 
>case 401: 
>-> throw new DataSift_Exception_AccessDenied( 
>empty($res['data']['error']) ? 'Authentication failed' : $res['data']['error'] 
>); 
>case 413: 
>at DataSift_User ->handleResponse (array('response_code' => '401', 'data' => array('error' => 'Authorization credentials missing'), 'rate_limit' => '-1', 'rate_limit_remaining' => '-1')) 
>in vendor/datasift/datasift-php/lib/DataSift/User.php at line 605 
>at DataSift_User ->put ('account/identity/96f668665060e212ad0572d202ea507f/token/facebook', null, array('token' => '1078932352135050|7f11d3ff8e0bec5900f998a343afd57f')) 
>in vendor/datasift/datasift-php/lib/DataSift/Account/Identity/Token.php at line 97 
>at DataSift_Account_Identity_Token ->update ('96f668665060e212ad0572d202ea507f', 'facebook', '1078932352135050|7f11d3ff8e0bec5900f998a343afd57f') 
>in src/Datasift/ConnectBundle/Service/IdentityService.php at line 374
>
>Additionally this response triggers a PHP Notice: Undefined variable: successCode in vendor/datasift/datasift-php/lib/DataSift/Account/Identity/Token.php on line 97
>
>Delete token: 
>Triggers PHP Fatal Error: Call to undefined method DataSift_Account_Identity_Token::call() in vendor/datasift/datasift-php/lib/DataSift/Account/Identity/Token.php on line 113

**Comment by paulmozo** [comment]
Hi,
The first error you are receiving `Content was expected but nothing was returned (Status: 201 and no data)` is the result of a bug in the Datasift API rather than the PHP client library. Currently upon token creation you will receive a 201 but no content is returned by the API, which is why the exception is thrown. The work around for the time being is to catch the exception, make sure you received a 201, then use a token get to retrieve the token that was just created. We are already aware of the issue and the team responsible for the API are looking in to it. 

The other errors you mentioned should now be addressed by the latest version of the PHP client. If you do notice any other errors feel free to open a new issue or comment on this one.

I'm going to close this issue for now but will get back to you with details of the API bug in your support ticket.
